[workspace]
members = [
    "pisshoff-server",
    "pisshoff-timescaledb-exporter",
    "pisshoff-types"
]

[patch."crates-io"]
thrussh = { git = "ssh://git@github.com/JordanForks/thrussh" }
thrussh-keys = { git = "ssh://git@github.com/JordanForks/thrussh" }
